version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: "increase"
    commit-message:
      prefix: "[Docs Site] "
    schedule:
      interval: "daily"
    assignees:
      - "kodster28"
    reviewers:
      - "kodster28"
