#:schema ./node_modules/wrangler/config-schema.json
name = "cloudflare-docs"
account_id = "b54f07a6c269ecca2fa60f1ae4920c99"
compatibility_date = "2025-06-02"
compatibility_flags = ["nodejs_compat"]
main = "./worker/index.ts"

workers_dev = true
route = { pattern = "developers.cloudflare.com/*", zone_name = "developers.cloudflare.com" }

rules = [
	{ type = "Text", globs = ["**/__redirects"], fallthrough = true },
]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "404-page"
run_worker_first = true

[[r2_buckets]]
binding = "VENDORED_MARKDOWN"
bucket_name = "vendored-markdown"

[observability]
enabled = true