name: Configuration Rules

product:
  title: Configuration Rules
  group: Application performance
  url: /rules/configuration-rules/
  show: false

meta:
  title: Cloudflare Configuration Rules docs
  author: "@cloudflare"